<a href="https://colab.research.google.com/github/dongminkim0220/pytorch_tutorial/blob/master/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd

PyTorch Tutorial 03 - Gradient Calculation With Autograd

https://www.youtube.com/watch?v=DbeIqrwb_dE&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=3

In [2]:
import torch

In [15]:
x = torch.randn(3, requires_grad=True)

In [16]:
x

tensor([0.6470, 0.6624, 0.7667], requires_grad=True)

In [17]:
y = x + 2

In [18]:
y

tensor([2.6470, 2.6624, 2.7667], grad_fn=<AddBackward0>)

In [19]:
z = y * y * 2

In [20]:
z

tensor([14.0136, 14.1766, 15.3089], grad_fn=<MulBackward0>)

In [21]:
z = z.mean()

In [22]:
z

tensor(14.4997, grad_fn=<MeanBackward0>)

In [23]:
z.backward() # dz/dx

In [24]:
z

tensor(14.4997, grad_fn=<MeanBackward0>)

In [26]:
x.grad

tensor([3.5294, 3.5498, 3.6889])

In [27]:
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)

## no grad

In [29]:
x.requires_grad_(False)

tensor([0.6470, 0.6624, 0.7667])

In [30]:
x

tensor([0.6470, 0.6624, 0.7667])

In [31]:
y = x.detach()

In [33]:
with torch.no_grad():
  y = x + 2
  print(y)

tensor([2.6470, 2.6624, 2.7667])


In [34]:
weights = torch.ones(4, requires_grad=True)

In [36]:
for epoch in range(1, 2):
  model_output = (weights * 3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([6., 6., 6., 6.])
