<a href="https://colab.research.google.com/github/dongminkim0220/pytorch_tutorial/blob/master/Softmax_and_Activation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Softmax, Activation

PyTorch Tutorial 11 - Softmax and Cross Entropy

https://www.youtube.com/watch?v=7q7E91pHoW4&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=11

PyTorch Tutorial 12 - Activation Functions

https://www.youtube.com/watch?v=3t9lZM7SS7k&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=12

In [29]:
import torch
import torch.nn as nn
import numpy as np

softmax

In [30]:
def softmax(x):
  return np.exp(x) / np.sum(np.exp(x), axis = 0)

In [31]:
x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)

In [32]:
outputs

array([0.65900114, 0.24243297, 0.09856589])

cross entropy

In [33]:
def cross_entropy(actual, predicted):
  loss = -np.sum(actual * np.log(predicted))
  return loss

In [34]:
Y = np.array([1, 0, 0])

In [35]:
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])

In [36]:
cross_entropy(Y, Y_pred_good)

0.35667494393873245

In [37]:
cross_entropy(Y, Y_pred_bad)

2.3025850929940455

pytorch

In [38]:
loss = nn.CrossEntropyLoss()

In [39]:
# nsamples: 1
Y = torch.tensor([0])

# nsamples x nclasses: 1 x 3
Y_pred_good = torch.tensor([[2,0, 1.0, 0.1]])
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])

In [40]:
loss(Y_pred_good, Y)

tensor(0.5025)

In [41]:
loss(Y_pred_bad, Y)

tensor(1.8406)

In [42]:
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)

In [43]:
predictions1

tensor([0])

In [44]:
predictions2

tensor([1])

Models with activation

In [45]:
import torch.nn.functional as F 

In [47]:
F.leaky_relu

<function torch.nn.functional.leaky_relu>