<a href="https://colab.research.google.com/github/dongminkim0220/pytorch_tutorial/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics


PyTorch Tutorial 02 - Tensor Basics: https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=3

# tensors

In [1]:
import torch

In [2]:
x = torch.empty(1)

In [3]:
x

tensor([2.7865e-08])

In [4]:
x = torch.empty(2, 3)

In [5]:
x

tensor([[2.7866e-08, 3.0667e-41, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])

In [6]:
x = torch.empty(2, 2, 2, 3)

In [7]:
x

tensor([[[[2.7910e-08, 3.0667e-41, 7.0065e-44],
          [6.8664e-44, 6.3058e-44, 6.7262e-44]],

         [[7.4269e-44, 6.3058e-44, 7.0065e-44],
          [6.7262e-44, 1.1771e-43, 6.7262e-44]]],


        [[[7.4269e-44, 8.1275e-44, 6.8664e-44],
          [7.7071e-44, 8.1275e-44, 6.8664e-44]],

         [[7.5670e-44, 6.4460e-44, 7.8473e-44],
          [6.7262e-44, 7.8473e-44, 7.4269e-44]]]])

## other options

In [8]:
x = torch.zeros(2, 2)

In [9]:
x

tensor([[0., 0.],
        [0., 0.]])

In [10]:
x = torch.ones(2, 2)

In [11]:
x

tensor([[1., 1.],
        [1., 1.]])

In [12]:
x.dtype

torch.float32

In [13]:
x = torch.ones(2, 2, dtype = torch.int)

In [14]:
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [15]:
x.size()

torch.Size([2, 2])

In [16]:
x = torch.tensor([2.5, 0.1])

In [17]:
x

tensor([2.5000, 0.1000])

## tensor operations

In [18]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [19]:
z = x + y

In [20]:
z

tensor([[1.0190, 0.2455],
        [1.3606, 0.6505]])

In [21]:
z = torch.add(x, y)

In [22]:
z

tensor([[1.0190, 0.2455],
        [1.3606, 0.6505]])

In [23]:
y.add_(x) # underscore: in-place operations

tensor([[1.0190, 0.2455],
        [1.3606, 0.6505]])

In [24]:
z = x - y

In [25]:
z

tensor([[-0.9604, -0.1647],
        [-0.4304, -0.1031]])

In [26]:
z = torch.sub(x, y)

In [27]:
z

tensor([[-0.9604, -0.1647],
        [-0.4304, -0.1031]])

In [28]:
z = torch.mul(x, y)

In [29]:
z

tensor([[0.0597, 0.0198],
        [1.2656, 0.3561]])

In [30]:
y.mul_(x)

tensor([[0.0597, 0.0198],
        [1.2656, 0.3561]])

In [31]:
x = torch.rand(5, 3)

In [32]:
x

tensor([[0.4298, 0.8248, 0.3611],
        [0.4357, 0.8794, 0.7727],
        [0.1147, 0.8737, 0.7540],
        [0.7448, 0.6446, 0.6607],
        [0.7955, 0.1254, 0.6026]])

In [33]:
x[:, 0]

tensor([0.4298, 0.4357, 0.1147, 0.7448, 0.7955])

In [34]:
 x[1, 1]

tensor(0.8794)

In [35]:
x[1, 1].item()

0.8794028162956238

## reshaping

In [36]:
x = torch.rand(4, 4)

In [37]:
x

tensor([[0.4983, 0.2641, 0.2569, 0.2868],
        [0.5217, 0.5723, 0.7867, 0.0479],
        [0.3284, 0.7114, 0.0186, 0.2879],
        [0.1354, 0.6177, 0.5068, 0.0235]])

In [38]:
y = x.view(16)

In [39]:
y

tensor([0.4983, 0.2641, 0.2569, 0.2868, 0.5217, 0.5723, 0.7867, 0.0479, 0.3284,
        0.7114, 0.0186, 0.2879, 0.1354, 0.6177, 0.5068, 0.0235])

## numpy

In [42]:
import numpy as np

In [48]:
a = torch.ones(5)

In [49]:
a

tensor([1., 1., 1., 1., 1.])

In [50]:
b = a.numpy()

In [51]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [53]:
b # a, b shares same memory!

array([2., 2., 2., 2., 2.], dtype=float32)

In [54]:
a = np.ones(5)

In [55]:
b = torch.from_numpy(a)

In [56]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [57]:
a += 1

In [58]:
a

array([2., 2., 2., 2., 2.])

## device

In [60]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device = device)
  y = torch.onse(5)
  y = y.to(device)
  z = x + y # on gpu
  # z.numpy() # numpy handles only cpu
  z = z.to("cpu") # on cpu again
else:
  print("cuda not available")

cuda not available


In [61]:
x = torch.ones(5, requires_grad=True)

In [62]:
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)